Add the uaa_ctl changes

diff --git a/jobs/uaa/templates/uaa_ctl.erb b/jobs/uaa/templates/uaa_ctl.erb
--- a/jobs/uaa/templates/uaa_ctl.erb
+++ b/jobs/uaa/templates/uaa_ctl.erb
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+echo "[uaa-ctl] UAA Control Setting Up Logging"
+echo "[uaa-ctl] UAA Control script invoked"
 export PATH=/var/vcap/packages/uaa/jdk/bin:$PATH
 RUN_DIR=/var/vcap/sys/run/uaa
 LOG_DIR=/var/vcap/sys/log/uaa
@@ -11,14 +13,15 @@ STATUS=/var/vcap/jobs/uaa/bin/status
 # Proxy configuration variable for the uaa
 HTTP_PROXY_JAVA_OPTIONS=""
 
+echo "[uaa-ctl] Default environment set up"
 # Minimum strength for password
 # TODO: move into correct properties file that is local to UAA war file only
 UAA_OPTIONS="-Dpassword-policy.required-score=0"
 
 if [[ -f /var/vcap/jobs/uaa/config/cacerts ]]; then
-    export KEYSTORE="/var/vcap/jobs/uaa/config/cacerts"
+  export KEYSTORE="/var/vcap/jobs/uaa/config/cacerts"
 else
-    export KEYSTORE="/var/vcap/packages/uaa/jdk/jre/lib/security/cacerts"
+  export KEYSTORE="/var/vcap/packages/uaa/jdk/jre/lib/security/cacerts"
 fi
 
 export KEYSTORE_OPTS="-Djavax.net.ssl.trustStore=$KEYSTORE -Djavax.net.ssl.trustStoreType=JKS"
@@ -30,12 +33,14 @@ export http_proxy='<%= httpProxy %>'
 proxy_conf=(`echo $HTTP_PROXY | tr ":" " " | tr "\/" " "`)
 HTTP_PROXY_JAVA_OPTIONS="$HTTP_PROXY_JAVA_OPTIONS -Dhttp.proxyHost=${proxy_conf[1]} -Dhttp.proxyPort=${proxy_conf[2]} "
 <% end %>
+
 <% if_p('env.https_proxy') do |httpsProxy| %>
 export HTTPS_PROXY='<%= httpsProxy %>'
 export https_proxy='<%= httpsProxy %>'
 proxy_conf=(`echo $HTTPS_PROXY | tr ":" " " | tr "\/" " "`)
 HTTP_PROXY_JAVA_OPTIONS="$HTTP_PROXY_JAVA_OPTIONS -Dhttps.proxyHost=${proxy_conf[1]} -Dhttps.proxyPort=${proxy_conf[2]} "
 <% end %>
+
 <% if_p('env.no_proxy') do |noProxy| %>
 export NO_PROXY='<%= noProxy %>'
 export no_proxy='<%= noProxy %>'
@@ -57,6 +62,7 @@ if [ x != x"$NO_PROXY" ]; then
   HTTP_PROXY_JAVA_OPTIONS="$HTTP_PROXY_JAVA_OPTIONS -Dhttp.nonProxyHosts=\"$java_no_proxies\" "
 fi
 <% end %>
+echo "[uaa-ctl] UAA System Proxies set to:$HTTP_PROXY_JAVA_OPTIONS"
 
 NEWRELIC_OPTS=
 <% if_p('uaa.newrelic') do |newrelic|
@@ -70,6 +76,7 @@ NEWRELIC_OPTS=
 end %>
 
 export NEWRELIC_OPTS
+echo "[uaa-ctl] UAA New Relic set to:$NEWRELIC_OPTS"
 
 mkdir -p /var/vcap/sys/log
 
@@ -119,15 +126,16 @@ case $1 in
 
     if pid_guard $PIDFILE "UAA"
     then
-      echo "[uaa-start] UAA not running - proceeding with startup"
+      echo "[uaa-start] UAA not running according to pid_guard - proceeding with startup"
     else
-      echo "[uaa-check] UAA already running - check successful...."
-      exit 0
+      echo "[uaa-start] UAA already running according to pid_guard - aborting start process"
+      exit 1
     fi
 
     echo "[uaa-start] About to starting UAA"
     ensure_no_more_tomcat
 
+    echo "[uaa-start] Creating health check STATUS file"
     touch $STATUS
     echo "[uaa-start] Health check STATUS file created"
 
@@ -141,7 +149,9 @@ case $1 in
     chown vcap:vcap $PIDFILE
 
     <% if p('uaa.ldap.sslCertificate', nil) || p('login.ldap.sslCertificate', nil) %>
+    echo "[uaa-start] Installing LDAP certificate"
     /var/vcap/jobs/uaa/bin/install_crt ldap.crt ldapcert $KEYSTORE
+    echo "[uaa-start] Installed LDAP certificate"
     <% end %>
 
     # Generate a random username and password for varz
@@ -166,7 +176,9 @@ case $1 in
 
     # Install the server's ssl certificate
     <% if !p("uaa.sslCertificate").empty? %>
-        /var/vcap/jobs/uaa/bin/install_uaa_crt uaa.crt
+    echo "[uaa-start] Installing Server SSL certificate"
+    /var/vcap/jobs/uaa/bin/install_uaa_crt uaa.crt
+    echo "[uaa-start] Installed Server SSL certificate"
     <% end %>
 
     cd /var/vcap/data/uaa
@@ -177,21 +189,25 @@ case $1 in
 
   stop)
     echo "[uaa-stop] About to stop UAA"
+    # This tells the health_check to return false
+    # and the route will be deregistered
     rm -f $STATUS
     sleep 5
     echo "[uaa-stop] Health check STATUS file removed"
-    if [ -f $PIDFILE ]; then
-      echo "[uaa-stop] Found UAA Tomcat PID file $PIDFILE - Killing `cat $PIDFILE`"
-      kill `cat $PIDFILE`
-      rm -rf $PIDFILE
-      sleep 5
+    if pid_guard $PIDFILE "UAA"
+    then
+        echo "[uaa-check] UAA not running"
+    else
+        echo "[uaa-stop] Found UAA Tomcat PID file $PIDFILE - Killing `cat $PIDFILE`"
+        kill `cat $PIDFILE`
+        rm -rf $PIDFILE
+        sleep 5
     fi
+    echo "[uaa-stop] Clearing left over java processes"
     ensure_no_more_tomcat
     ;;
-
   *)
     echo "Usage: uaa_ctl {start|stop}"
-
     ;;
 
 esac
